import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    accordion: "src/components/accordion.tsx",
    alert: "src/components/alert.tsx",
    "app-card": "src/components/app-card.tsx",
    avatar: "src/components/avatar.tsx",
    "avatar-group": "src/components/avatar-group.tsx",
    badge: "src/components/badge.tsx",
    breadcrumb: "src/components/breadcrumb.tsx",
    button: "src/components/button.tsx",
    callout: "src/components/callout.tsx",
    card: "src/components/card.tsx",
    "category-pill": "src/components/category-pill.tsx",
    chart: "src/components/chart.tsx",
    checkbox: "src/components/checkbox.tsx",
    "code-block": "src/components/code-block.tsx",
    collapsible: "src/components/collapsible.tsx",
    command: "src/components/command.tsx",
    "context-menu": "src/components/context-menu.tsx",
    "data-table": "src/components/data-table.tsx",
    "date-picker": "src/components/date-picker.tsx",
    dialog: "src/components/dialog.tsx",
    divider: "src/components/divider.tsx",
    dropdown: "src/components/dropdown.tsx",
    "dropdown-menu": "src/components/dropdown-menu.tsx",
    "empty-state": "src/components/empty-state.tsx",
    field: "src/components/field.tsx",
    form: "src/components/form.tsx",
    "form-sidebar": "src/components/form-sidebar.tsx",
    icon: "src/components/icon.tsx",
    input: "src/components/input.tsx",
    label: "src/components/label.tsx",
    list: "src/components/list.tsx",
    "page-form-header": "src/components/page-form-header.tsx",
    "page-header": "src/components/page-header.tsx",
    "page-search-header": "src/components/page-search-header.tsx",
    pagination: "src/components/pagination.tsx",
    pills: "src/components/pills.tsx",
    popover: "src/components/popover.tsx",
    progress: "src/components/progress.tsx",
    radio: "src/components/radio.tsx",
    "rule-group": "src/components/rule-group.tsx",
    "rule-row": "src/components/rule-row.tsx",
    search: "src/components/search.tsx",
    "search-v3": "src/components/search-v3.tsx",
    select: "src/components/select.tsx",
    separator: "src/components/separator.tsx",
    sheet: "src/components/sheet.tsx",
    sidebar: "src/components/sidebar.tsx",
    skeleton: "src/components/skeleton.tsx",
    slider: "src/components/slider.tsx",
    stack: "src/components/stack.tsx",
    stat: "src/components/stat.tsx",
    "status-pill": "src/components/status-pill.tsx",
    switch: "src/components/switch.tsx",
    table: "src/components/table.tsx",
    "table-pagination": "src/components/table-pagination.tsx",
    tabs: "src/components/tabs.tsx",
    tag: "src/components/tag.tsx",
    "targeting-category-card": "src/components/targeting-category-card.tsx",
    "targeting-rule-builder": "src/components/targeting-rule-builder.tsx",
    textarea: "src/components/textarea.tsx",
    toast: "src/components/toast.tsx",
    toggle: "src/components/toggle.tsx",
    tooltip: "src/components/tooltip.tsx",
    typography: "src/components/typography.tsx",
  },
  format: ["cjs", "esm"],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom", "tailwindcss"],
  treeshake: true,
});
